version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - echo test completed
artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes
